# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: dwbi_backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dwbi
    username: root
    password: 963852
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 963852
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
yuapi:
  client:
    access-key: k69as97b1dy3dg6rr106byw5udowgpq8
    secret-key: nbrasn18iuv7jvas4144keu0j621xy32
alipay:
  appId: 9021000134665993
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCfQ0YMJjy6XZBFyJoCXcgugTfFIXtWbMctDW8zN7ShoMiiVl0M0TrNWCqbdyHigt/z6Gr1dguoFW3r6E3ejW2CEwTxr3j+ujFS0Fy0Kr3U9uO4NJt611uDBnjQUDvGb61lOI5Hj9+50D/5KUdhSPg2rxg+QQKbX8mb0MbHJOzjaisMXBEHe+ebZnrQkdj+GZ0qRglxSrh+rXJqAjhimLkxkLu8MYDK8jj43aD9Abc6MKVwep0p7otn2mhszCp317QXMFC2xfwoIL9NqARSMRb+L15l7RbLi7qFiTcaAZcaRdnoEDnT5wMoA7FHYp8fXLXERqZP+OWoMU6Sib67/+bZAgMBAAECggEAZlR2ZIYJDQHjGkN7WTvizKawK9SIiA5ap8LzCSiowhUp9Myi+wJQ0vHsZnnUZtMKjJBwcQkJElW6jBJ2PiIHE8Werp+9kYYW/QvuFMFFudlslcYPhI1tOjHlXIvA7I6DDf+Zw7dY2+5HvJNeTs7w1UoJvK5Ou4B/bMNnhTtfjfp2iw3qxFFXOpoLJC35RJ9wSeXOPPY3u8x/zRJZcnV83JDKTcdjNkfeLG1jX9xywa3z5Ucll623RIgFWOztcl2ibTHzUhzIFWAHnIqnewibAUJi5nBixnf1EBdVrwADP+Oj+3trK+O2n5kZvAhcrtczvjf1oVi2lgpkCVivxS57gQKBgQD8GLY6RVJBK5xjVvo8f+XGw/PYgROkeDzx4pkvA0Ly779cMV5HPgOn2NKUxP05FYrwsYD38HPXpgx3b4k0x3q/qTs+27vLQkZ3bHZ+bFOYKmg5i/GSny+TpIeqA9r0nywwTrTfwmzydVNreRF9y+kDZWcbjsJbkeG4zycPSFiM8QKBgQChupO9zpH5+AQtKkXW/4IhG67V0iAIaD6RXAhNnAO5XkpDmoxnvPo2XoMkgTcf9As0iOwkynj51u3HvZC88pFkM5FgKKARFtP+pJwpp/nNGFVnAM9tP58PJodCEF8GuDe9Ba2glQGzcXnSsMa2+gxP3l4M6HW/en0Fvg40V++YaQKBgQCGu2ZZCkeF0RsJ9KhUwT461utyILowwpo/5I1eFO4pDH1HdpMenEQz5qvVGtsDMUJKlXOKD5a6AGLVSmUYMiymVnn1hFZ/sXIbzXoe4yJiRvfhGawIYs94pwxijyDscE2bm9ULacv0YUQuQkxY4SwtxnouvkOd0P/EV+JWRqIc4QKBgDzQDmvJuAQ5aUCea6J7czAF28kU+OyQXi6EX67nIlNajCw9edwsKB23jjJ00AiY2HnJnpn69GBlnAWGV11lDJyT828n94BViCNxPDNBsWGYa8yOdnDLAoFM6IFD7Kd3L6ZI80+1l+0klz1NMXtuLKD/qXfLFTOJ2GcHXwn5ouM5AoGBANJF/jRYSMXI6/v8NLyKD8w/eYrpYK7VAOZoPHOPejQHUc2CWhGg3p/iWveEZb0eTGAdQQuyOxB8C2p2cvhxu3GCmiSM0LCWVhqGHHOeswzu+DI83EZZb5Mr9z0x5yQ0qhkO9pSlABuZ33n4vs2HVNTp3MykRX0hSYmNVQIo/Kbs
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAovAISkKzq85/VbHQDFCiLJ4JFp6hK9cEU34f68ronMKL3jaeHPcA/Ach9NhNx/i2JqVvzcLcvg5jpYgKhAHtPiYDMFOqH6TjZDhz925M2VGzWowvP7pW59vqP7dFBgacjp1cP247rMgratv1elwFGDSnVdwlsGNcqm15ZdSmSnySn0omYMJ/YXZujDe0ggg7oUt5EB6f4nSfH0jFaORAdISUTi6EDtTpXSWC5Kd6iTmBLgvXlr1sDGFgVSDxwM+i+7bA1ZDFEFNndi6GtLBiBMMG13rkLnGN7vk+bz/6RM3Q14xvmPZXbHb6JpTxOWCarOhFpqXacT4oR3/WaUteOwIDAQAB